name: Build and Release Extension

on:
  push:
    tags:
      - 'v*.*.*'  # Match version tags, like v1.0.0

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-js-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Compile TypeScript
      run: npm run compile
      
    - name: Install vsce
      run: npm install -g vsce
      
    - name: Package extension
      run: vsce package
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Trae Usage Monitor v${{ steps.get_version.outputs.VERSION }}
          
          ### Features
          - Real-time Trae AI usage monitoring
          - Token usage statistics
          - Visual usage dashboard in VSCode
          - Configurable refresh intervals

          ### Installation
          1. Install the `.vsix` file or search "Trae Usage Monitor" in Extensions Store
          2. Configure your Trae AI authentication token in settings
          3. View usage statistics in the Explorer panel
        files: |
          *.vsix
        draft: false
        prerelease: false
        
    # Auto-publish to VSCode Marketplace
    - name: Publish to VSCode Marketplace
      run: vsce publish -p ${{ secrets.VSCE_PAT }}
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      
    # Auto-publish to OpenVSX Registry
    - name: Install ovsx
      run: npm install -g ovsx
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      
    - name: Publish to OpenVSX Registry
      run: ovsx publish *.vsix -p ${{ secrets.OVSX_PAT }}
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')